<?php
/**
 * TikTokShop WebhookEventExtensionInterface
 *
 * This file is a stub for IDE and linter support.
 * The actual class will be auto-generated by Magento during setup:di:compile
 *
 * @author    AfterShip <support@aftership.com>
 * @copyright 2023 AfterShip
 * @license   MIT http://opensource.org/licenses/MIT
 * @link      https://aftership.com
 */

namespace AfterShip\TikTokShop\Api\Data;

use Magento\Framework\Api\ExtensionAttributesInterface;

/**
 * Extension attributes interface for WebhookEvent.
 *
 * This interface will be auto-generated by Magento based on extension_attributes.xml
 *
 * @author   AfterShip <support@aftership.com>
 * @license  MIT http://opensource.org/licenses/MIT
 * @link     https://aftership.com
 */
interface WebhookEventExtensionInterface extends ExtensionAttributesInterface
{
    /**
     * Get product change type
     *
     * @return string|null
     */
    public function getProductChangeType();

    /**
     * Set product change type
     *
     * @param string $productChangeType
     * @return $this
     */
    public function setProductChangeType($productChangeType);
}

